apiVersion: batch/v1
kind: CronJob
metadata:
  name: nifty-predict
  namespace: market-forecast
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nifty-predict
              image: hiteshk283/forecast:15
              command:
                - python
                - -m
                - app.scripts.update_and_predict
              volumeMounts:
                - name: nifty-storage
                  mountPath: /app/data
                - name: nifty-storage
                  mountPath: /app/models
          restartPolicy: OnFailure
          volumes:
            - name: nifty-storage
              persistentVolumeClaim:
                claimName: nifty-pvc
