apiVersion: batch/v1
kind: CronJob
metadata:
  name: nifty-predict
  namespace: market-forecast
spec:
  schedule: "*/5 * * * *"   # every 5 minutes (change if needed)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nifty-predict
              image: localhost:5000/market-forecast:latest
              command:
                - python
                - app/scripts/update_and_predict.py
              volumeMounts:
                - name: nifty-storage
                  mountPath: /app/data
                - name: nifty-storage
                  mountPath: /app/models
          restartPolicy: OnFailure
          volumes:
            - name: nifty-storage
              persistentVolumeClaim:
                claimName: nifty-pvc
