apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifty-ingress
  namespace: market-forecast
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nifty.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nifty-service
            port:
              number: 80
