apiVersion: v1
kind: Service
metadata:
  name: nifty-service
  namespace: market-forecast
spec:
  type: NodePort
  selector:
    app: nifty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
